version: '3'
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: docker-compose.env
    command: python ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
  
  postgres:
    image: postgres:11.4-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data
    env_file: docker-compose.env

volumes:
  postgres_data: